name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: 'package.json'

      - name: Install dependencies
        run: |
          pnpm install

      - name: run CI
        env:
          SGL_IP: ${{ secrets.SGL_IP }}
          SGL_PORT: ${{ secrets.SGL_PORT }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          pushd js
          pnpm run ci
          popd
          pushd studio
          pnpm run ci
          popd
          pushd docs
          pnpm run ci
          popd
