name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: "package.json"

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pnpm install
          pushd python
          pip install ".[dev]"
          popd
          pushd studio-python
          pip install ".[dev]"
          popd
          pip install pre-commit

      - name: run CI
        env:
          SGL_IP: ${{ secrets.SGL_IP }}
          SGL_PORT: ${{ secrets.SGL_PORT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pushd js
          pnpm run ci
          popd
          pushd studio
          pnpm run ci
          popd
          pushd docs
          pnpm run ci
          popd
          pushd python
          ./.ci.sh
          popd
          pushd studio-python
          ./.ci.sh
          popd
