name: Publish

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'js/.nvmrc'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: 'js/package.json'

      - name: Install dependencies
        run: |
          pushd js
          pnpm install

      - name: Build package
        run: |
          pushd js
          pnpm run ci

      - name: Create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: |
          pushd js
          npm publish
